export const API_ROUTES = {
  health: "/api/v1/health",
  auth: {
    register: "/api/v1/auth/register",
    login: "/api/v1/auth/login",
    me: "/api/v1/auth/me",
  },
  organizations: "/api/v1/organizations",
  oauth: {
    googleStart: "/api/v1/oauth/google/start",
    slackStart: "/api/v1/oauth/slack/start",
  },
  integrations: {
    list: "/api/v1/integrations",
    refresh: (integrationId: string) => `/api/v1/integrations/${integrationId}/refresh`,
    syncNow: (integrationId: string) => `/api/v1/integrations/${integrationId}/sync`,
    gmailWatch: (integrationId: string) => `/api/v1/integrations/${integrationId}/gmail/watch`,
    calendarWatch: (integrationId: string) => `/api/v1/integrations/${integrationId}/calendar/watch`,
    driveWatch: (integrationId: string) => `/api/v1/integrations/${integrationId}/drive/watch`,
  },
  actions: {
    execute: "/api/v1/actions/execute",
  },
  events: {
    manual: "/api/v1/events/manual",
    timeline: "/api/v1/events/timeline",
  },
  emails: "/api/v1/emails",
  threads: "/api/v1/threads",
  meetings: "/api/v1/meetings",
  documents: "/api/v1/documents",
  document: (documentId: string) => `/api/v1/documents/${documentId}`,
  documentContent: (documentId: string) => `/api/v1/documents/${documentId}/content`,
  documentSheet: (documentId: string) => `/api/v1/documents/${documentId}/sheet`,
  documentAppend: (documentId: string) => `/api/v1/documents/${documentId}/append`,
  projects: "/api/v1/projects",
  deals: "/api/v1/deals",
  approvals: "/api/v1/approvals",
  briefs: "/api/v1/briefs",
  tasks: {
    list: "/api/v1/tasks",
    update: (taskId: string) => `/api/v1/tasks/${taskId}`,
  },
  chat: {
    message: "/api/v1/chat/message",
    stream: "/api/v1/chat/stream",
  },
  agents: {
    dailyBrief: "/api/v1/agents/daily-brief",
    meetingSummary: "/api/v1/agents/meeting-summary",
    schedule: "/api/v1/agents/schedule",
  },
  // Operational intelligence
  commitments: {
    list: "/api/v1/commitments",
    overdue: "/api/v1/commitments/overdue",
    waiting: "/api/v1/commitments/waiting",
    summary: "/api/v1/commitments/summary",
    update: (id: string) => `/api/v1/commitments/${id}`,
    nudge: (id: string) => `/api/v1/commitments/${id}/nudge`,
  },
  goals: {
    list: "/api/v1/goals",
    create: "/api/v1/goals",
    update: (id: string) => `/api/v1/goals/${id}`,
  },
  intelligence: {
    calendarAnalysis: "/api/v1/calendar/analysis",
    calendarOpportunities: "/api/v1/calendar/opportunities",
    weeklyPlan: "/api/v1/calendar/weekly-plan",
    meetingPrepUpcoming: "/api/v1/meeting-prep/upcoming",
    meetingPrep: (id: string) => `/api/v1/meeting-prep/${id}`,
    kpiDashboard: "/api/v1/kpi/dashboard",
    kpiAnomalies: "/api/v1/kpi/anomalies",
    kpiIngest: "/api/v1/kpi/ingest",
    crisisAssess: "/api/v1/crisis/assess",
    decisions: "/api/v1/decisions",
    risks: "/api/v1/risks",
    people: "/api/v1/people",
    followUps: "/api/v1/follow-ups",
    agentActions: "/api/v1/agent-actions",
    agentActionsPending: "/api/v1/agent-actions/pending",
    agentActionApprove: (id: string) => `/api/v1/agent-actions/${id}/approve`,
    agentActionReject: (id: string) => `/api/v1/agent-actions/${id}/reject`,
    preferences: "/api/v1/preferences",
  },
  composio: {
    tools: "/api/v1/composio/tools",
    toolkits: "/api/v1/composio/toolkits",
    connect: "/api/v1/composio/connect",
  },
  workspaces: {
    list: "/api/v1/workspaces",
    create: "/api/v1/workspaces",
    get: (id: string) => `/api/v1/workspaces/${id}`,
    update: (id: string) => `/api/v1/workspaces/${id}`,
    delete: (id: string) => `/api/v1/workspaces/${id}`,
  },
  contextQuestions: {
    list: "/api/v1/context-questions",
    answer: (id: string) => `/api/v1/context-questions/${id}/answer`,
    context: "/api/v1/context-questions/context",
  },
} as const;
